server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/shipment_tracking
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
    open-in-view: false
  sql:
    init:
      mode: never

app:
  jwt:
    secret: "91PZilZbjm2K4BjmtI0iUmRcdnQup+wLgE48zeWwp+tXPwyt4dBM7GP9sMqTy8yy"
  rate-limit:
    requests-per-minute: 1000
